### ISSUE TITLE
Can't import MDL into Create-React-App with version 2.29.0

### ISSUE THREAD

**Issue by AlexGarrisonMercury** [masonitedoors/MDL#152]
**Do you want to request a _feature_ or report a _bug_?**
_bug_

**What is the current behavior?**
Importing from `@masonite/external-ui-react` throws error on app load. 

**If the current behavior is a bug, please provide the steps to reproduce and if possible a minimal demo of the problem. Paste the link to your JSFiddle (https://jsfiddle.net/Luktwrdm/) or CodeSandbox (https://codesandbox.io/s/new) example below:**
- Open any `create-react-app` application
- Install or update to latest version of React MDL `yarn add @masonite/external-ui-react`
- Start the application `yarn start`
- Try to import any component from the MDL `import { Button } from '@masonite/external-ui-react';`
- See error when page attempts to load changes `ReferenceError: require is not defined`

**What is the expected behavior?**
Application loads with no errors.

**Which versions of MDL, and which browser / OS are affected by this issue? Did this work in previous versions of MDL?**
v2.29.0, Chrome 87.0.4280.88, Windows 10

**Solution**
- open `/config/webpack.config.js` 
- change line 67 from `mode: 'development',` to `mode: 'production',`
- rebuild

**Comment by AlexGarrisonMercury** [comment]
PR for this issue: https://github.com/masonitedoors/MDL/pull/153

**Comment by tarikhamilton** [comment]
@AlexGarrisonMercury Deployed as well, thanks again for contributing.

**Comment by AlexGarrisonMercury** [comment]
Yeah no problem
