### ISSUE TITLE
Flatten component hierarchy

### ISSUE THREAD

**Issue by josephfusco** [masonitedoors/MDL#20]
We have buttons in forms right now but buttons are not exclusive to forms. Same could be said about the filterable search.

![CleanShot 2019-03-22 at 11 04 29](https://user-images.githubusercontent.com/6676674/54833569-b9f19980-4c94-11e9-84db-9cc286423aff.png)

**Comment by simonwebdesign** [comment]
@josephfusco Your call! Just keep me looped.
