### ISSUE TITLE
Change the component naming convention

### ISSUE THREAD

**Issue by tarikhamilton** [masonitedoors/MDL#22]
I want us rename component files using this template: `[framework].[type].[ext]`

Example: `stories.react.js` => `react.stories.js`

Why? Well, that's how tests are (`.spec.js`, `.test.js`). That's how config files are (think: `webpack.config.js`, `vue.config.js`). That's how quite a few modifiers are. 

So, I think we should rename these somewhat soon.

**Comment by josephfusco** [comment]
To avoid creating merge conflicts, this can be worked on once https://github.com/masonitedoors/MDL/pull/57 is merged. 😃
