### ISSUE TITLE
Fix @masonite/svg-icons build

### ISSUE THREAD

**Issue by tarikhamilton** [masonitedoors/MDL#30]
Only 1.0.2 works. Haven't really investigated further.

**Comment by josephfusco** [comment]
@tarikhamilton

I ran a diff against the latest release that isn't working (1.0.4) with the last working release (1.0.2) and discovered that the key problem being that the `dist/` directory is missing from the latest published release.

**Comment by tarikhamilton** [comment]
@josephfusco Thanks for looking into this. That very well may be it. The files really only need to be present when deploying the package to NPM.

Here is the build file. 
https://github.com/masonitedoors/MDL/blob/master/packages/svg-icons/build.js

**Comment by josephfusco** [comment]
Closing since this has been fixed in https://github.com/masonitedoors/MDL/releases/tag/%40masonite%2Fsvg-icons%401.1.0

Thanks @tarikhamilton 🙌
